parameters:
- name: buildMigrationScript
  type: boolean
  default: false

stages:
  - stage: DeprecationWarning
    displayName: DEPRECATED - Repository Has Moved
    jobs:
      - job: ShowDeprecationWarning
        displayName: Show Deprecation Warning
        steps:
          - bash: |
              echo "##vso[task.logissue type=warning]DEPRECATED: This Azure DevOps template repository has moved to GitHub."
              echo "##vso[task.logissue type=warning]New location: https://github.com/DEFRA/epr-webapps-code-deploy-templates"
              echo "##vso[task.logissue type=warning]Please update your pipeline references to use the new GitHub repository."
              echo ""
              echo "========================================"
              echo "  DEPRECATION NOTICE"
              echo "========================================"
              echo ""
              echo "  This template repository has moved to GitHub."
              echo ""
              echo "  New location:"
              echo "  https://github.com/DEFRA/epr-webapps-code-deploy-templates"
              echo ""
              echo "  Please update your pipeline to use the new repository."
              echo ""
              echo "========================================"
            displayName: Deprecation Warning

  - stage: doingOWASPandDockerBuild
    dependsOn: DeprecationWarning
    jobs:

    - job: RunOWASPTests
      displayName: Run OWASP Dependency checks
      steps:
        - template: templates/owaspcheck.yaml
          parameters:
            solutionFolder: $(solutionFolder)
            projectFolder: $(testProjectFolder)

    - job: BuildAndPushDockerImage
      displayName: Build and Push Docker Image
      dependsOn: RunOWASPTests
      steps:
        - template: templates/docker.yaml
          parameters:
            azureSubscription: $(azureSubscription)
            solutionFolder: $(solutionFolder)
            projectFolder: $(projectFolder)
            azureContainerRegistryName: $(acr.azureContainerRegistryName)
            repositoryName: $(acr.repositoryName)
            branchName: ${{ replace(replace(variables['Build.SourceBranch'], 'refs/heads/', ''), '/', '_') }}

    - job: BuildAndPushDockerImageSQLMigrationScript
      displayName: Build and Push Docker Image - Migration Script
      dependsOn: BuildAndPushDockerImage
      condition: eq('${{parameters.buildMigrationScript}}', true)
      steps:
        - template: templates/docker-sql-migration-script.yaml
          parameters:
            azureSubscription: $(azureSubscription)
            solutionFolder: $(solutionFolder)
            projectFolder: $(projectFolder)
            azureContainerRegistryName: $(acr.azureContainerRegistryName)
            repositoryName: $(acr.repositoryName)
            branchName: ${{ replace(replace(variables['Build.SourceBranch'], 'refs/heads/', ''), '/', '_') }}