name: OSV wrapper (PR)
on:
  workflow_call:
    inputs:
      fail-on-vuln:
        type: boolean
        default: false        # non-blocking for now
      upload-sarif:
        type: boolean
        default: true
      scan-args:
        type: string
        default: |-
          --recursive
          ./
      sarif-category:
        type: string
        default: osv-scanner-pr
jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Run OSV-Scanner
        continue-on-error: ${{ !inputs.fail-on-vuln }}
        uses: google/osv-scanner-action/osv-scanner-action@9a498708959aeaef5ef730655706c5a1df1edbc2 # v2.3.8
        with:
          scan-args: |-
            --format=sarif
            --output=results.sarif
            ${{ inputs.scan-args }}

      - name: Upload SARIF to code scanning
        if: ${{ inputs.upload-sarif && always() }}
        uses: github/codeql-action/upload-sarif@24c7eb380a2dc368f2d129e4c65e51d172983a1e # v4.30.9
        with:
          sarif_file: results.sarif
          category: ${{ inputs.sarif-category }}

      - name: Upload SARIF artefact
        if: ${{ always() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.0
        with:
          name: osv-results-pr
          path: results.sarif
          if-no-files-found: warn
